### ISSUE TITLE
Add "Latest" and "Latest LTS" to the "Select Release" combo box

### ISSUE THREAD

**Issue by maverick74** [tushev/aojdk-updatewatcher#1]
Add "Latest" and "Latest LTS" to the "Select Release" combo box so that, this way, one can set it to always live on the Latest LTS release or in the Latest Release, what ever the number might be, and just forget about it as opposed to having to manually change the version every time a new major release is out.

**Comment by tushev** [comment]
@maverick74 I think I will implement this in the next release of the updater. However, currently I cannot say when exactly it will be ready.

**Comment by maverick74** [comment]
Nice!

Would be cool if it wouldn't take too long :)

**Comment by tushev** [comment]
@maverick74 Version 2, released just now, implements this feature.

You can find more info here: https://github.com/tushev/aojdk-updatewatcher/wiki/Using-%22Most-recent%22-feature

**Comment by maverick74** [comment]
Great news!!! :)

I've also liked that it allows us to download the aojdk from the program :) (we´ll talk more about this bellow...)

1. About the program, i think i found a bug: 

when i choose that i wanted to install a new instance, a new window pops-up and i get to choose, on the "Major Version" option, that i want the "Most Recent" version.
However, after it downloads and installs the desired software version, the update software assumes the value "15" instead of "Most Recent". When version 16 get's out will it update?


2. A suggestion about the wonderful option to get aojdk from the software:

Would be great that Either during the install process it would detect if there's no aojdk and offer to install it OR do this on the first run of the program, without one needing to go to the configurations screen and click on "Download and install".

**Comment by tushev** [comment]
@maverick74 , "it's not a bug, it's a feature" :) (c)

Actually, the app behaves like intended. It discovers aojdk from the registry and applies default settings, which means staying on Branch 15. 

"Always upgrade to most recent" is a non-standard (even potentially dangerous and compatibility breaking) feature, so the user must **explicitly opt-in**. To do so, you should explicitly override auto-discovered settings, as suggested here: https://github.com/tushev/aojdk-updatewatcher/wiki/Using-%22Most-recent%22-feature.

I agree that there may be a little misunderstanding from the UX perspective: the user downloads "most recent" JRE and expects it to keep updating as "most recent branch". However, some other user may download "just the latest" JRE, but does not expect that suddenly one day JRE updates to next branch and possibly breaks compatibility. The app always stays on the safe side, as recommended by Java community guidelines.

Maybe I should add a little clarification about this in UI&help.

> Would be great that Either during the install process it would detect if there's no aojdk and offer to install it OR do this on the first run of the program, without one needing to go to the configurations screen and click on "Download and install".

Thank you for your suggestion! The app will always open configuration screen on fresh install (not upgrade), so the user will not miss it. As for install process option, I should see whether it's possible to add it.

**Comment by maverick74** [comment]
> @maverick74 , "it's not a bug, it's a feature" :) (c)
> 
> Actually, the app behaves like intended. It discovers aojdk from the registry and applies default settings, which means staying on Branch 15.
> 
> "Always upgrade to most recent" is a non-standard (even potentially dangerous and compatibility breaking) feature, so the user must **explicitly opt-in**. To do so, you should explicitly override auto-discovered settings, as suggested here: https://github.com/tushev/aojdk-updatewatcher/wiki/Using-%22Most-recent%22-feature.
> 
> I agree that there may be a little misunderstanding from the UX perspective: the user downloads "most recent" JRE and expects it to keep updating as "most recent branch". However, some other user may download "just the latest" JRE, but does not expect that suddenly one day JRE updates to next branch and possibly breaks compatibility. The app always stays on the safe side, as recommended by Java community guidelines.
> 
> Maybe I should add a little clarification about this in UI&help.

I see... Its better your way, no doubt! And how about an opt-in checkbox to "always keep on this branch" when user chooses the branch?

It plays the safe side but lets users choose to keep on the latest version...

> 
> > Would be great that Either during the install process it would detect if there's no aojdk and offer to install it OR do this on the first run of the program, without one needing to go to the configurations screen and click on "Download and install".
> 
> Thank you for your suggestion! The app will always open configuration screen on fresh install (not upgrade), so the user will not miss it. As for install process option, I should see whether it's possible to add it.

Nice :)

**Comment by tushev** [comment]
> And how about an opt-in checkbox to "always keep on this branch" when user chooses the branch?

Nice idea, but I'm afraid it could be rather hard to implement: to do it, the app should somehow "track" the actions of MSI being currently installed and get its **result** installation path to create a manual override. AFAIK, there is no easy way to do it. As well, the path could be changed by user during installation process, + MSI usually uninstalls previous version, user can download and install several MSIs at once - this all complicates things a little for just one checkbox :)
