### ISSUE TITLE
Configure AJUpdater not available if using ZIP release

### ISSUE THREAD

**Issue by MakiabelMFE** [tushev/aojdk-updatewatcher#4]
**Describe the bug**
As title says, there is no shortcut in start menu to configure AJUpdater after first run if installed by extracting the zip file.
**I'm sure that it's not a 'known-not-a-bug'**
**See**: https://github.com/tushev/aojdk-updatewatcher/wiki/Known-not-a-bugs
[X] Yes

**To Reproduce**
1. Download, extract and run AJUpdater
2. Do nothing and close the window
3. Run it again to be met by the silent updates notice with info on how to configure it
4. Can't run it because no start menu shortcut is created

**Expected behavior**
Some way of configuring the updater after running the first config even if it was just extracted from a zip.
**Screenshots**
Not needed
**Desktop (please complete the following information):**
 - App Version 2.0.0.0 latest

**Additional context**

**Comment by tushev** [comment]
Hi,

in this case you should create the shortcut manually as described in the picture, or just run `AJUpdateWatcher.exe` with `-config` parameter from command line.

![image](https://user-images.githubusercontent.com/18406797/98451402-02f6aa00-2167-11eb-8631-d603f5a0ab74.png)

I think I will provide .cmd/.bat file for this in the next release.

**Comment by tushev** [comment]
Just released https://github.com/tushev/aojdk-updatewatcher/releases/tag/2.0.1.0

The issue is solved.
