### ISSUE TITLE
AdoptOpenJdk has moved/rebrended to Adoptium

### ISSUE THREAD

**Issue by Bryksin** [tushev/aojdk-updatewatcher#44]
AdoptOpenJdk was rebrended to Adoptium https://adoptium.net/

Original AdoptOpenJdk has only JDK16, whereas Adoptium has already 17. Would be amazing if you would update your watcher to use new Adoptium

**Comment by tushev** [comment]
Thank you for your suggestion. 

Current ([v.2.0.4.0](https://github.com/tushev/aojdk-updatewatcher/releases/tag/2.0.4.0)) of my updater is still branded as `Update Watcher for AdoptOpenJDK *`, but it allows to install and update<br>Eclipse Adoptium (Temurin) 17 binaries:
![image](https://user-images.githubusercontent.com/18406797/151409337-e69f087c-e4d2-4c2a-a358-56529255e3cc.png)

![image](https://user-images.githubusercontent.com/18406797/151408420-a2b4d187-8548-42d6-90d2-f83a63bd5e8f.png)

Do you see these values in your updater? It should detect installed JDK/JRE **MSI's** automatically. UnZIPped instances may require adding them manually.

<hr>

As for name change, I'm planning to rebrand simultaneously with the switch from **api.adoptopenjdk.net** to **api.adoptium.net**. This will be done after either IBM releases its own API for Semeru (ex. AdoptOpenJDK openj9 builds) or **api.adoptium.net** would start providing Semeru releases (https://github.com/adoptium/api.adoptium.net/issues/187) .
