### ISSUE TITLE
Add ability to connect through proxy

### ISSUE THREAD

**Issue by tonibony** [tushev/aojdk-updatewatcher#6]
I installed this app on a Windows system, which connects to Internet only through http proxy. The proxy settings are configured at system level. When I start the app configurator, an error box pop-ups, saying "Unable to get list of AdoptOpenJDK releases". Using the web browser, I can access https://api.adoptopenjdk.net/v3/info/available_releases and I see the result (a JSON document). Also, I don't see any hint in the app configuration UI and documentation about using a proxy.

I will be pleased if there is a way to use the app with at least http proxy.

**Comment by pjhavariotis** [comment]
> I installed this app on a Windows system, which connects to Internet only through http proxy. The proxy settings are configured at system level. When I start the app configurator, an error box pop-ups, saying "Unable to get list of AdoptOpenJDK releases". Using the web browser, I can access https://api.adoptopenjdk.net/v3/info/available_releases and I see the result (a JSON document). Also, I don't see any hint in the app configuration UI and documentation about using a proxy.
> 
> I will be pleased if there is a way to use the app with at least http proxy.

Well said @tonibony ! Proxy support is a **must** for such software!

**Comment by tushev** [comment]
Hello, thank you for your feedback. Yes, proxy is not supported currently.

I think I will add proxy support in the next release (2.0.2). 

However, there is no release date yet.

**Comment by tushev** [comment]
@tonibony @pjhavariotis 

I need your help. I've added support for Windows default proxy (<kbd>Win+R</kbd>: `ms-settings:network-proxy`), so the updater will reuse global configuration. However, I don't have a proxy, so, please test the following pre-release https://github.com/tushev/aojdk-updatewatcher/releases/tag/2.0.1.1 
and tell me whether it works or not in real scenarios.

*Preferred - backup the existing `C:\Program Files\AJUpdateWatcher` dir and just overwrite its contents from the ZIP, restore back once tested.*

**Comment by pjhavariotis** [comment]
I have just tested the pre-release and it seems is working! To be specific, I executed the "Run immediate checks for updates" command, and after a while the screen showed up with the corresponding updates! Finally, I updated my JDK with the latest version without any issue!

**Comment by tushev** [comment]
@pjhavariotis great! I will include this functionality in the next release then. The release, however, may take a bit longer as there are some other things to implement...

**Comment by tonibony** [comment]
Yep, it's working in my case too! I've tested showing the configuration dialog and the "Check for AdoptOpenJDK updates" button on it.

**Comment by tushev** [comment]
@tonibony Great, thanks!

The only untested item left is self-update - once v. 2.0.2 will be released publicly, your updaters should pick it. However, self-update uses exactly the same code, so it should be working as well.

**Comment by tushev** [comment]
Released https://github.com/tushev/aojdk-updatewatcher/releases/tag/2.0.2.0

Your pre-release version should pick it up automatically, please confirm.

**Comment by pjhavariotis** [comment]
Confirmed !
Happy New Year !
Be Safe !

**Comment by tushev** [comment]
@pjhavariotis Thank you, you too! Happy New Year!! 🎄
