### ISSUE TITLE
Error: [Configuration system failed to initialize]

### ISSUE THREAD

**Issue by IO2I** [tushev/aojdk-updatewatcher#65]
**Describe the bug**
Update watcher won't launch

**I'm sure that it's not a 'known-not-a-bug'**
**Check** https://github.com/tushev/aojdk-updatewatcher/wiki/Known-not-a-bugs
[X] Yes

**To Reproduce**
1. Launch either an update check or the configuration

**Expected behavior**
Successful update check

**Screenshots**
![Screenshot 2023-04-24 002702](https://user-images.githubusercontent.com/16938966/233900223-ec0782ae-41bb-4320-96f1-d8d841892f4e.png)

**Desktop (please complete the following information):**
 - App Version 2.0.4
 - Windows Version Windows 11 22H2
 - JDKs/JREs Temurin 17.0.7+7

**Additional context**
Tried a fresh install of updatewatcher with the same result

**Comment by tushev** [comment]
Hello,

try deleting the following file: **%USERPROFILE%**\AppData\Local\tushev.org\AJUpdateWatcher.exe_Url_**SOME_RANDOM_STRING**\2.0.4.0\user.config

**Comment by IO2I** [comment]
Seems to have worked. Thanks for the help!
