### ISSUE TITLE
Icons missing in Windows 7/8

### ISSUE THREAD

**Issue by necik** [tushev/aojdk-updatewatcher#7]
There are icons missing in both Configuration and Check windows (see attached pictures). It is version 2.0.1.0 (was the same in previous versions too) and it is the same on both of my computers - one Windows 8 and the other Windows 7.

![UpdateWatcherCheck](https://user-images.githubusercontent.com/6862010/102695085-79d29880-4225-11eb-84e9-3fbde002eb95.png)
![UpdateWatcherConfiguration](https://user-images.githubusercontent.com/6862010/102695086-7a6b2f00-4225-11eb-9a3a-64a0e5e3f7ab.png)

**Comment by tushev** [comment]
Thank you for your report.

Update Watcher uses now-recommended **[Segoe MDL2 Assets](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)** font for icons, which is missing in Windows 7/8. Unfortunately, I'm not aware whether Microsoft licensing terms allow installing that font on other versions of Windows.

**Comment by necik** [comment]
Installing Segoe MDL2 Assets font helped, thanks.
