### ISSUE TITLE
Program fails to launch, gives error [Configuration system failed to initialize]

### ISSUE THREAD

**Issue by hero-rareheart** [tushev/aojdk-updatewatcher#76]
For several weeks on my system the application has opened to an error dialogue reading "There was an error: [Configuration system failed to initialize]". I have attempted to reinstall the application with no success.

![image](https://github.com/tushev/aojdk-updatewatcher/assets/139519751/e5addd04-66d1-4643-b268-cadc3c53aac0)

 - App Version 2.0.5.0
 - Windows 11 Pro 22H2
 - Temurin 17.0.10+7, Temurin 8u402-b02-b06

I am very new to submitting bugs, please let me know what I can do to improve this report or what other helpful information I can provide.

**Comment by tushev** [comment]
See https://github.com/tushev/aojdk-updatewatcher/issues/65
